### ISSUE TITLE
Cross Country

### ISSUE THREAD

**Issue by RohanHarikumar** [RohanHarikumar/ICS3U#1]
Ready for marking.

**Comment by kevindeslauriers** [comment]
Good Job - Rohan!  The only issues were that you did not place a block comment at the top of you code summarizing the assignment. You also did not prompt by first name only and you asked for all of the runner names at the beginning.

![rohan harikumar - rubric cross country assignment_page_1](https://cloud.githubusercontent.com/assets/739858/4891223/d99488ce-63a5-11e4-931f-a714b5da6635.jpg)
![rohan harikumar - rubric cross country assignment_page_2](https://cloud.githubusercontent.com/assets/739858/4891224/d997032e-63a5-11e4-9cc2-d4630378456a.jpg)
